# PR labeler configuration file
ci:
- any: ['.github/**/*','!.github/ISSUE_TEMPLATE/*','!.github/pull_request_template.md']
- pipelines/**/*
- .pre-commit-config.yaml

gitignore:
- .gitignore

github_actions:
- any: ['.github/**/*','!.github/ISSUE_TEMPLATE/*','!.github/pull_request_template.md']

tests:
- any: ['tests/**/*']

documentation:
- docs/**/*
- .readthedocs.yaml
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- README.md
- SECURITY.md
- .github/ISSUE_TEMPLATE/**/*
- .github/pull_request_template.md

configuration:
- pyproject.toml
- setup.py

python:
- '**/*.py'

dependencies:
- requirements.txt
- requirements-*.txt
- requirements/**/*.txt
